### ISSUE TITLE
Semantic Segmentation

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/drydock_ros#3]
- [x] use the general stub provided bby @RoboCtrl in #2 to integrate detectron-based segmentation
- [x] use data set to train at least 4 classes: canopy, berry, rigid structures, background

optionally the depth image is available if it helps with segmenting background etc.

**Comment by marc-hanheide** [comment]
@usmanzahidi , have you had any luck with the data?

**Comment by usmanzahidi** [comment]
Yes, I fetched 800 depth aligned images from mongo. Will show annotations
and predictions in the meeting.

Regards,
Usman

**Comment by marc-hanheide** [comment]
Please share link to code so, @RoboCtrl has access to start wrapping into Action Server

**Comment by usmanzahidi** [comment]
Here it is; https://github.com/usmanzahidi/MaskPredictor.git
model shared with @RoboCtrl
